### ISSUE TITLE
Unable to download docker image (has it been removed ?)

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [panrafal/depthy#45]
Hi,
following the documentation, I tried the following:
`docker run --rm -t -i -p 9000:9000 essembeh/depthy`
But I had an error "The system cannot find the file specified."
I'm not sure if it is due to my firewall at work so I need to try it at home.

HOWEVER I noticed on the docker hub that the image is not present when I search for 'essembeh'
https://hub.docker.com/search?q=essembeh&type=image
From what I understand of issue #18 it has been put online in 2014 by @essembeh but now it seems removed.
Please note that I'm a true beginner with docker so I may have missed something, in that case juste tell me where to look for the docker image.

**Comment by essembeh** [comment]
Hi @Celeborn2BeAlive 

I'm really sorry, I didn't receive any notfication when you created the ticket.

I sent a PR to @panrafal to integrate a docker file but if the git repository is not linked via webhook to the docker repository, the docker image is not rebuilt every time the git repository is updated.
As I'm not a depthy developper, I couldn't setup the docker and git repositories together to automate the docker image builds. 
I only published a demo docker image which became totally outdated because I didn't rebuild it that often.

Recently, I cleaned up some outdated docker images which I did not maintain, that is why you cannot pull essembeh/depthy.

But, you might be able to build the docker image yourself (but it is based on a ubuntu which is EOL).
```
$ docker build --tag depthy:latest https://github.com/panrafal/depthy.git
$ docker run --rm -t -i -p 9000:9000 depthy:latest
```

Have fun

**Comment by ndahlquist** [comment]
I've uploaded a new Docker image here:

```
docker run --rm -t -i -p 9000:9000 ndahlquist/depthy
```

(I've also made a PR to update the readme here: #48)

**Comment by danielemaddaluno** [comment]
@ndahlquist could you share the Dockerfile you have used to create that image?
I tried with this one: [depthy/docker/Dockerfile](https://github.com/panrafal/depthy/blob/master/docker/Dockerfile)
but it gives me errors.

**Comment by ndahlquist** [comment]
Here it is! https://github.com/LeiaInc/depthy/blob/master/Dockerfile

(Not sure if this will work; haven't touched this in years)

**Comment by danielemaddaluno** [comment]
Thank you very much
